[[redirects]]\n from = "/"\n to = "https://smartsync-download.netlify.app/app-debug.apk"\n status = 301\n force = false\n\n[[headers]]\n for = "/*"\n [headers.values]\n Access-Control-Allow-Origin = "*"
