name: "Build"

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Build
        run: |
         cd android
         chmod +x gradlew
         ./gradlew assembleDebug
      - name: Push to released Repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: app/build/outputs/apk/debug/
          destination-github-username: 'mrepol742'
          destination-repository-name: 'smartsync'
          user-email: mrepol742@gmail.com
          commit-message: Initial Commit
          target-branch: build